version: '3'

services:
  api:
    build: .
    ports: 
      - 8080:8080
    environment:  
      - MONGO_URI=mongodb://mongodb:27017
      - MONGO_DATABASE_NAME=test
      - MONGO_COLLECTION_NAME=users
      - SERVICE_PORT=8080
  
  mongodb:
    image: mongo:3.4.14
    ports:
      - 27017:27017
    command: mongod --smallfiles