version: '3'

services:
  api:
    build: .
    env_file: 
      - secrets.env
    ports: 
       - 8080:8080 
  
  mongodb:
    image: mongo:3.4.14
    ports:
      - 27017:27017
    command: mongod --smallfiles